theme: jekyll-theme-minimal
title: Representation of Arabs in cinema before and after 9/11
description: description
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
